// <auto-generated />
using LaBenVi_CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaBenVi_CouponAPI.Migrations
{
    [DbContext(typeof(LaBenViDbContext))]
    [Migration("20240105163034_Coupon")]
    partial class Coupon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaBenVi_CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "967DD",
                            DiscountAmount = 38.0,
                            MinAmount = 150
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "700FG",
                            DiscountAmount = 40.0,
                            MinAmount = 80
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "589AF",
                            DiscountAmount = 200.0,
                            MinAmount = 400
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "769FD",
                            DiscountAmount = 50.0,
                            MinAmount = 750
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "200WS",
                            DiscountAmount = 45.0,
                            MinAmount = 950
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
